### PR TITLE
Update to Prisma v4

### LINKED ISSUE #34: Upcoming rename of `@prisma/sdk` to `@prisma/internals` with Prisma 4
Hey,

Jan from Prisma Engineering here.
 
Quick heads up that we will soon rename our `@prisma/sdk` package to `@prisma/internals` with Prisma 4, which we plan to release on June 28th (soon!). 

The `@prisma/sdk` package was meant as an Prisma internal package only, but somehow it leaked out over time and is now used across all kinds of tools - including yours of course 😄

With the rename of the Npm package we want to make it clearer that we can not give any API guarantees for `@prisma/internals`, might need to introduce breaking changes to the API from time to time and will not follow semantic versioning (breaking changes only in major upgrade) with it. We think that it is better communicated with `internals` than with `sdk`.
With Prisma 4, besides the package name nothing should change though.

Additionally it would be super helpful if you could help us gain an understanding where, how and why you are using `@prisma/sdk` (soon `@prisma/internals`, remember 😀) to achieve, what exactly. We want to cleanup that package and your feedback will be valuable to us to define a better API.

Looking forward to your feedback.

Best
Jan & your friends at Prisma

PS: Are you using `Prisma.dmmf` from `import { Prisma } from '@prisma/client'` in your code somewhere by chance? That will also change soon and not include the `Prisma.dmmf.schema` sub property. Instead you can use `getDmmf` from `@prisma/internals` moving forward.

### PR DESCRIPTION
**Pull request by PabloSzx**
Closes #34

### CODE REVIEW

**Comment by PabloSzx** [comment]
cc @marcjulian

**Comment by PabloSzx** [comment]
image
there seems to be another issue that isn't caught by the tests, because when generating in a reasonably sized project it's frozen, when removing the dbml generator provider it does generate correctly

**Review by marcjulian — APPROVED** [review]
LGTM!

**Comment by marcjulian** [comment]
@PabloSzx thanks again for the PR!

I released a dev version to test it out

```bash
npm i -D prisma-dbml-generator@0.10.0-dev.0
```

**Pull request merged**
