### PR TITLE
fixes: 26 fix to resolve multiple single quote 

### PR DESCRIPTION
**Pull request by doflo-dfa**
update to fix the broken replacement of multiple occurrences of single quotes

### CODE REVIEW

**Comment by marcjulian** [comment]
You need to apply this also for inline notes, see https://github.com/notiz-dev/prisma-dbml-generator/blob/main/src/generator/table.ts#L98

**Comment by doflo-dfa** [comment]
updated test...

**Comment by doflo-dfa** [comment]
fixed inline comments

**Comment by marcjulian** [comment]
Thanks again! I will create a bug fix release

**Pull request merged**
